[tool.poetry]
name = "auto-qc"
version = "2.0.0"
description = 'Run high-throughput automated quality control using configuration files.'
authors = ["Michael Barton <mail@michaelbarton.me.uk>"]

[tool.poetry.dependencies]
python = "^3.8"
python-termstyle = "^0.1.10"
PyYAML = "^5.3.1"
funcy = "^1.15"
fn = "^0.4.3"
pytest = "^6.2.1"

[tool.poetry.dev-dependencies]
rednose = "^1.3.0"
scripttest = "^1.3"
behave = "^1.2"
black = "^20.8b1"
nose = "1.3"
rich = "^9.6.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line_length = 100
