name: CI

on: [push]

env:
  TERM: xterm

jobs:

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.1.0

      - name: Run unit tests
        run: make test

